#!/bin/sh

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2011-present Alex@ELEC (http://alexelec.in.ua)

URL="$@"

################################################################################
# Streamer: VLC | FFmpeg
################################################################################

STREAMER="FFmpeg"

CONFIG_FILE="/storage/.cache/services/tvlink.conf"
[ -f "$CONFIG_FILE" ] && . $CONFIG_FILE

if [ "$STREAMER" == "VLC" ]; then
  echo "*** IPTV stream TVLINK (vlc): $URL ***" >&2
  /usr/bin/cvlc --quiet --ipv4-timeout=10000 --network-caching=0 --no-drop-late-frames --no-skip-frames "$URL" --sout-mux-caching=0 --sout '#std{mux=ts,access=file,dst=-}'
else
  echo "*** IPTV stream TVLINK (ffmpeg): $URL ***" >&2
  /usr/bin/ffmpeg -v quiet -hide_banner -i "$URL" -flags nobuffer -flags low_delay -avioflags direct -strict experimental -max_muxing_queue_size 9999 -c copy -ignore_unknown -map 0 -f mpegts pipe:1
fi
