
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-24T20:54:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "af86d38af3441db5e73bafa53065cb01d6b4d6f7",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
